INSERT INTO STUDENTS (STUDENT_CODE, STUDENT_NAME, STUDENT_SURNAME, STUDENT_COLLEGE_NAME, STUDENT_PERIOD_COLLEGE_STARTED, STUDENT_BIRTH) VALUES ('A00018644', 'Jhon', 'Doe', 'Icesi', '15-1', '1997-05-21');

INSERT INTO ACCOUNTS (ACCOUNT_PHONE_NUMBER, ACCOUNT_PASSWORD, STUDENTS_STUDENT_ID) VALUES ('+573003556499', 'Some password', 1);